INSERT INTO marca (codigo, nome, tp_veiculo) VALUES
('102', 'AGRALE', 'CAMINHAO'),
('206', 'BEPOBUS', 'CAMINHAO'),
('103', 'CHEVROLET', 'CAMINHAO'),
('121', 'CICCOBUS', 'CAMINHAO'),
('197', 'DAF', 'CAMINHAO'),
('179', 'EFFA-JMC', 'CAMINHAO'),
('104', 'FIAT', 'CAMINHAO'),
('105', 'FORD', 'CAMINHAO'),
('191', 'FOTON', 'CAMINHAO'),
('106', 'GMC', 'CAMINHAO'),
('181', 'HYUNDAI', 'CAMINHAO'),
('122', 'IVECO', 'CAMINHAO'),
('188', 'JAC', 'CAMINHAO'),
('184', 'MAN', 'CAMINHAO'),
('108', 'MARCOPOLO', 'CAMINHAO'),
('196', 'MASCARELLO', 'CAMINHAO'),
('194', 'MAXIBUS', 'CAMINHAO'),
('109', 'MERCEDES-BENZ', 'CAMINHAO'),
('110', 'NAVISTAR', 'CAMINHAO'),
('111', 'NEOBUS', 'CAMINHAO'),
('112', 'PUMA-ALFA', 'CAMINHAO'),
('113', 'SAAB-SCANIA', 'CAMINHAO'),
('114', 'SCANIA', 'CAMINHAO'),
('193', 'SHACMAN', 'CAMINHAO'),
('166', 'SINOTRUK', 'CAMINHAO'),
('115', 'VOLKSWAGEN', 'CAMINHAO'),
('116', 'VOLVO', 'CAMINHAO'),
('144', 'WALKBUS', 'CAMINHAO');

INSERT INTO marca (codigo, nome, tp_veiculo) VALUES
('1', 'ACURA', 'CARRO'),
('2', 'AGRALE', 'CARRO'),
('3', 'ALFA ROMEO', 'CARRO'),
('4', 'AM GEN', 'CARRO'),
('5', 'ASIA MOTORS', 'CARRO'),
('189', 'ASTON MARTIN', 'CARRO'),
('6', 'AUDI', 'CARRO'),
('207', 'BABY', 'CARRO'),
('7', 'BMW', 'CARRO'),
('8', 'BRM', 'CARRO'),
('123', 'BUGRE', 'CARRO'),
('238', 'BYD', 'CARRO'),
('236', 'CAB MOTORS', 'CARRO'),
('10', 'CADILLAC', 'CARRO'),
('245', 'CAOA CHERY', 'CARRO'),
('161', 'CAOA CHERY/CHERY', 'CARRO'),
('11', 'CBT JIPE', 'CARRO'),
('136', 'CHANA', 'CARRO'),
('182', 'CHANGAN', 'CARRO'),
('12', 'CHRYSLER', 'CARRO'),
('13', 'CITROËN', 'CARRO'),
('14', 'CROSS LANDER', 'CARRO'),
('241', 'D2D MOTORS', 'CARRO'),
('15', 'DAEWOO', 'CARRO'),
('16', 'DAIHATSU', 'CARRO'),
('246', 'DFSK', 'CARRO'),
('17', 'DODGE', 'CARRO'),
('147', 'EFFA', 'CARRO'),
('18', 'ENGESA', 'CARRO'),
('19', 'ENVELO', 'CARRO'),
('20', 'FERRARI', 'CARRO'),
('21', 'FIAT', 'CARRO'),
('149', 'FIBRAVAN', 'CARRO'),
('22', 'FORD', 'CARRO'),
('190', 'FOTON', 'CARRO'),
('170', 'FYBER', 'CARRO'),
('199', 'GEELY', 'CARRO'),
('23', 'GM - CHEVROLET', 'CARRO'),
('153', 'GREAT WALL', 'CARRO'),
('24', 'GURGEL', 'CARRO'),
('240', 'GWM', 'CARRO'),
('152', 'HAFEI', 'CARRO'),
('214', 'HITECH ELECTRIC', 'CARRO'),
('25', 'HONDA', 'CARRO'),
('26', 'HYUNDAI', 'CARRO'),
('27', 'ISUZU', 'CARRO'),
('208', 'IVECO', 'CARRO'),
('177', 'JAC', 'CARRO'),
('28', 'JAGUAR', 'CARRO'),
('29', 'JEEP', 'CARRO'),
('154', 'JINBEI', 'CARRO'),
('30', 'JPX', 'CARRO'),
('31', 'KIA MOTORS', 'CARRO'),
('32', 'LADA', 'CARRO'),
('171', 'LAMBORGHINI', 'CARRO'),
('33', 'LAND ROVER', 'CARRO'),
('34', 'LEXUS', 'CARRO'),
('168', 'LIFAN', 'CARRO'),
('127', 'LOBINI', 'CARRO'),
('35', 'LOTUS', 'CARRO'),
('140', 'MAHINDRA', 'CARRO'),
('36', 'MASERATI', 'CARRO'),
('37', 'MATRA', 'CARRO'),
('38', 'MAZDA', 'CARRO'),
('211', 'MCLAREN', 'CARRO'),
('39', 'MERCEDES-BENZ', 'CARRO'),
('40', 'MERCURY', 'CARRO'),
('167', 'MG', 'CARRO'),
('156', 'MINI', 'CARRO'),
('41', 'MITSUBISHI', 'CARRO'),
('42', 'MIURA', 'CARRO'),
('43', 'NISSAN', 'CARRO'),
('44', 'PEUGEOT', 'CARRO'),
('45', 'PLYMOUTH', 'CARRO'),
('46', 'PONTIAC', 'CARRO'),
('47', 'PORSCHE', 'CARRO'),
('185', 'RAM', 'CARRO'),
('186', 'RELY', 'CARRO'),
('48', 'RENAULT', 'CARRO'),
('195', 'ROLLS-ROYCE', 'CARRO'),
('49', 'ROVER', 'CARRO'),
('50', 'SAAB', 'CARRO'),
('51', 'SATURN', 'CARRO'),
('52', 'SEAT', 'CARRO'),
('247', 'SERES', 'CARRO'),
('183', 'SHINERAY', 'CARRO'),
('157', 'SMART', 'CARRO'),
('125', 'SSANGYONG', 'CARRO'),
('54', 'SUBARU', 'CARRO'),
('55', 'SUZUKI', 'CARRO'),
('165', 'TAC', 'CARRO'),
('56', 'TOYOTA', 'CARRO'),
('57', 'TROLLER', 'CARRO'),
('58', 'VOLVO', 'CARRO'),
('59', 'VW - VOLKSWAGEN', 'CARRO'),
('163', 'WAKE', 'CARRO'),
('120', 'WALK', 'CARRO');

INSERT INTO marca (codigo, nome, tp_veiculo) VALUES
('60', 'ADLY', 'MOTO'),
('61', 'AGRALE', 'MOTO'),
('131', 'AMAZONAS', 'MOTO'),
('62', 'APRILIA', 'MOTO'),
('63', 'ATALA', 'MOTO'),
('216', 'AVELLOZ', 'MOTO'),
('64', 'BAJAJ', 'MOTO'),
('205', 'BEE', 'MOTO'),
('162', 'BENELLI', 'MOTO'),
('65', 'BETA', 'MOTO'),
('66', 'BIMOTA', 'MOTO'),
('67', 'BMW', 'MOTO'),
('68', 'BRANDY', 'MOTO'),
('130', 'BRAVA', 'MOTO'),
('150', 'BRP', 'MOTO'),
('117', 'BUELL', 'MOTO'),
('155', 'BUENO', 'MOTO'),
('212', 'BULL', 'MOTO'),
('69', 'BYCRISTO', 'MOTO'),
('70', 'CAGIVA', 'MOTO'),
('71', 'CALOI', 'MOTO'),
('72', 'DAELIM', 'MOTO'),
('145', 'DAFRA', 'MOTO'),
('137', 'DAYANG', 'MOTO'),
('142', 'DAYUN', 'MOTO'),
('73', 'DERBI', 'MOTO'),
('74', 'DUCATI', 'MOTO'),
('75', 'EMME', 'MOTO'),
('248', 'FEVER', 'MOTO'),
('132', 'FOX', 'MOTO'),
('209', 'FUSCO MOTOSEGURA', 'MOTO'),
('128', 'FYM', 'MOTO'),
('143', 'GARINNI', 'MOTO'),
('76', 'GAS GAS', 'MOTO'),
('133', 'GREEN', 'MOTO'),
('138', 'HAOBAO', 'MOTO'),
('203', 'HAOJUE', 'MOTO'),
('77', 'HARLEY-DAVIDSON', 'MOTO'),
('78', 'HARTFORD', 'MOTO'),
('79', 'HERO', 'MOTO'),
('80', 'HONDA', 'MOTO'),
('81', 'HUSABERG', 'MOTO'),
('82', 'HUSQVARNA', 'MOTO'),
('202', 'INDIAN', 'MOTO'),
('158', 'IROS', 'MOTO'),
('141', 'JIAPENG VOLCANO', 'MOTO'),
('174', 'JOHNNYPAG', 'MOTO'),
('151', 'JONNY', 'MOTO'),
('129', 'KAHENA', 'MOTO'),
('118', 'KASINSKI', 'MOTO'),
('85', 'KAWASAKI', 'MOTO'),
('87', 'KTM', 'MOTO'),
('204', 'KYMCO', 'MOTO'),
('159', 'LANDUM', 'MOTO'),
('88', 'L''AQUILA', 'MOTO'),
('89', 'LAVRALE', 'MOTO'),
('139', 'LERIVO', 'MOTO'),
('178', 'LIFAN', 'MOTO'),
('148', 'LON-V', 'MOTO'),
('175', 'MAGRÃO TRICICLOS', 'MOTO'),
('146', 'MALAGUTI', 'MOTO'),
('126', 'MIZA', 'MOTO'),
('90', 'MOTO GUZZI', 'MOTO'),
('201', 'MOTOCAR', 'MOTO'),
('200', 'MOTORINO', 'MOTO'),
('160', 'MRX', 'MOTO'),
('91', 'MV AGUSTA', 'MOTO'),
('92', 'MVK', 'MOTO'),
('239', 'NIU', 'MOTO'),
('93', 'ORCA', 'MOTO'),
('164', 'PEGASSI', 'MOTO'),
('94', 'PEUGEOT', 'MOTO'),
('95', 'PIAGGIO', 'MOTO'),
('210', 'POLARIS', 'MOTO'),
('173', 'REGAL RAPTOR', 'MOTO'),
('198', 'RIGUETE', 'MOTO'),
('192', 'ROYAL ENFIELD', 'MOTO'),
('96', 'SANYANG', 'MOTO'),
('134', 'SHINERAY', 'MOTO'),
('97', 'SIAMOTO', 'MOTO'),
('98', 'SUNDOWN', 'MOTO'),
('237', 'SUPER SOCO', 'MOTO'),
('99', 'SUZUKI', 'MOTO'),
('176', 'TARGOS', 'MOTO'),
('187', 'TIGER', 'MOTO'),
('119', 'TRAXX', 'MOTO'),
('100', 'TRIUMPH', 'MOTO'),
('244', 'VENTANE MOTORS', 'MOTO'),
('180', 'VENTO', 'MOTO'),
('215', 'VOLTZ', 'MOTO'),
('243', 'WATTS', 'MOTO'),
('135', 'WUYANG', 'MOTO'),
('101', 'YAMAHA', 'MOTO'),
('242', 'ZONTES', 'MOTO');